apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixfrontend-deployment
  labels:
    app: netflixfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflixfrontend
  template:
    metadata:
        labels:
          app: netflixfrontend
    spec:
      containers:
      - name: netflixfrontend
        image: ygalidan/netflixfrontend:v1.0.35
        env:
          - name: MOVIE_CATALOG_SERVICE
            value: http://netflixmoviecatalog-service:8080